subset_of_shots: 8
local: true

store_manager_settings:
  base_local_zarr_path: ./data  # REMARK: Only relevant when `local` above is true.

dataloader_setting:
  batch_size: 2
  num_workers: 0 #16
  # shuffle: True

training_args:
  lr: 0.0001
  # max_epochs: 500
  max_steps: 1000
  patience: 3

paths:
  data_output_directory: /output_test