subset_of_shots: 8
shuffle: false
local: true

store_manager_settings:
  base_local_zarr_path: ./data  # REMARK: Only relevant when `local` above is true.

dataloader_setting:
  batch_size: 4
  num_workers: 2 #16
  # shuffle: True

training_args:
  lr: 0.0001
  max_steps: 500
  patience: 3

# Transformer world-model hyper-parameters (only used when --model transformer).
wm:
  D: 16
  embed_dim:
  embed_dim_act:
  mem_window:

predictor:
  depth: 4
  heads: 4
  dim_head: 32
  mlp_dim:
  dropout: 0.1
  emb_dropout: 0.0

paths:
  data_output_directory: /output_test