subset_of_shots: 
local: true

dataloader_setting:
  batch_size: 512
  num_workers: 8 #16
  # shuffle: True

training_args:
  lr: 0.0001
  # max_epochs: 500
  max_steps: 10000000
  patience: 10

paths:
  data_output_directory: /output