subset_of_shots: 
shuffle: true
local: true

store_manager_settings:
  base_local_zarr_path: /rds/project/rds-mOlK9qn0PlQ/fairmast/upload-tmp/level2  # REMARK: Only relevant when `local` above is true.

dataloader_setting:
  batch_size: 512 #512
  num_workers: 8 #16

training_args:
  lr: 0.0001 #0.0001
  max_steps: 10000000
  patience: 10

paths:
  data_output_directory: /output