subset_of_shots: 
local: true

cnn_settings:
  D: 16

dataloader_setting:
  # batch_size: 64
  # num_workers: 8
  batch_size: 32
  num_workers: 32
  shuffle: True

training_args:
  # lr: 0.00001
  lr: 0.0001 # was working with 0.001
  max_epochs: 500 #500
  patience: 5

paths:
  data_output_directory: /output/cnn_model/